# Generated by Django 5.1.4 on 2026-09-02 17:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tracker', '0002_application_source_posting_alter_application_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='application',
            name='cover_letter_drive_url',
            field=models.URLField(blank=True, max_length=500),
        ),
        migrations.AddField(
            model_name='application',
            name='resume_drive_url',
            field=models.URLField(blank=True, max_length=500),
        ),
    ]
