# Generated by Django 5.1.4 on 2026-09-02 23:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tracker', '0004_alter_application_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='application',
            name='status',
            field=models.CharField(choices=[('saved', 'Saved'), ('ready', 'Ready to submit'), ('approved', 'Approved to send'), ('applied', 'Applied'), ('phone_screen', 'Phone screen'), ('interview', 'Interview'), ('offer', 'Offer'), ('rejected', 'Rejected'), ('withdrawn', 'Withdrawn'), ('discarded', 'Removed')], default='saved', max_length=20),
        ),
    ]
