# Generated by Django 5.1.4 on 2026-09-04 17:14

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tracker', '0006_application_owner'),
        # Not auto-detected: nothing in this app's own models points at
        # identity's data migration, but every row must have an owner backfilled
        # before this migration makes the column NOT NULL.
        ('identity', '0006_backfill_owner'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterField(
            model_name='application',
            name='owner',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='applications', to=settings.AUTH_USER_MODEL),
        ),
    ]
