# Generated by Django 5.1.4 on 2026-09-01 01:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('identity', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='professionalprofile',
            name='master_resume',
            field=models.TextField(blank=True),
        ),
    ]
