# Generated by Django 5.1.4 on 2026-09-01 13:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('identity', '0002_professionalprofile_master_resume'),
    ]

    operations = [
        migrations.AddField(
            model_name='professionalprofile',
            name='city_state',
            field=models.CharField(blank=True, max_length=120),
        ),
        migrations.AddField(
            model_name='professionalprofile',
            name='email',
            field=models.EmailField(blank=True, max_length=254),
        ),
        migrations.AddField(
            model_name='professionalprofile',
            name='legal_name',
            field=models.CharField(blank=True, max_length=200),
        ),
        migrations.AddField(
            model_name='professionalprofile',
            name='linkedin_url',
            field=models.URLField(blank=True),
        ),
        migrations.AddField(
            model_name='professionalprofile',
            name='phone',
            field=models.CharField(blank=True, max_length=50),
        ),
        migrations.AddField(
            model_name='professionalprofile',
            name='portfolio_url',
            field=models.URLField(blank=True),
        ),
    ]
