# Generated by Django 5.1.4 on 2026-09-02 20:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('identity', '0003_professionalprofile_city_state_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='professionalprofile',
            name='postal_code',
            field=models.CharField(blank=True, max_length=20),
        ),
        migrations.AddField(
            model_name='professionalprofile',
            name='street_address',
            field=models.CharField(blank=True, max_length=200),
        ),
    ]
