# Generated by Django 5.1.4 on 2026-09-04 19:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('identity', '0007_alter_professionalprofile_owner_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='resumeversion',
            name='discarded_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
