# Generated by Django 5.1.4 on 2026-10-09 15:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("identity", "0012_googledriveconnection"),
    ]

    operations = [
        migrations.AddField(
            model_name="jobfilterpreferences",
            name="distance",
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name="jobfilterpreferences",
            name="easy_apply",
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name="jobfilterpreferences",
            name="home_label",
            field=models.CharField(blank=True, max_length=120),
        ),
        migrations.AddField(
            model_name="jobfilterpreferences",
            name="home_latitude",
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="jobfilterpreferences",
            name="home_longitude",
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="jobfilterpreferences",
            name="posted_date",
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name="jobfilterpreferences",
            name="radius_miles",
            field=models.PositiveSmallIntegerField(default=25),
        ),
        migrations.AddField(
            model_name="jobfilterpreferences",
            name="sort",
            field=models.CharField(
                choices=[
                    ("best", "Best match"),
                    ("newest", "Newest"),
                    ("pay", "Highest pay"),
                    ("closest", "Closest"),
                    ("company", "Company A–Z"),
                ],
                default="best",
                max_length=10,
            ),
        ),
        migrations.AlterField(
            model_name="jobfilterpreferences",
            name="remote",
            field=models.BooleanField(default=True),
        ),
    ]
