# Generated by Django 5.1.4 on 2026-08-31 23:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ingestion', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ingestedposting',
            name='source',
            field=models.CharField(help_text='e.g. apify:indeed, rss:indeed, email', max_length=100),
        ),
        migrations.AlterField(
            model_name='ingestedposting',
            name='url',
            field=models.URLField(blank=True, max_length=1000),
        ),
        migrations.AddConstraint(
            model_name='ingestedposting',
            constraint=models.UniqueConstraint(condition=models.Q(('url', ''), _negated=True), fields=('source', 'url'), name='unique_posting_per_source_url'),
        ),
    ]
