# Generated by Django 5.1.4 on 2026-09-01 01:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ingestion', '0002_alter_ingestedposting_source_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='ingestedposting',
            options={'ordering': ['-score', '-created_at']},
        ),
        migrations.AddField(
            model_name='ingestedposting',
            name='apply_url',
            field=models.URLField(blank=True, max_length=1000),
        ),
        migrations.AddField(
            model_name='ingestedposting',
            name='score',
            field=models.PositiveSmallIntegerField(db_index=True, default=0),
        ),
        migrations.AddField(
            model_name='ingestedposting',
            name='score_reasons',
            field=models.JSONField(blank=True, default=list),
        ),
    ]
