# Generated by Django 5.1.4 on 2026-09-01 01:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ingestion', '0003_alter_ingestedposting_options_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='ingestedposting',
            name='generated_materials',
            field=models.JSONField(blank=True, default=dict),
        ),
    ]
