# Generated by Django 5.1.4 on 2026-09-02 22:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ingestion', '0006_unique_posting_per_url'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ingestedposting',
            name='status',
            field=models.CharField(choices=[('new', 'New'), ('triaged', 'Triaged'), ('dismissed', 'Dismissed'), ('expired', 'No longer listed')], default='new', max_length=20),
        ),
    ]
