# Generated by Django 5.1.4 on 2026-09-04 17:13

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ingestion', '0007_alter_ingestedposting_status'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name='ingestedposting',
            name='unique_posting_per_url',
        ),
        migrations.AddField(
            model_name='ingestedposting',
            name='owner',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='ingested_postings', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddConstraint(
            model_name='ingestedposting',
            constraint=models.UniqueConstraint(condition=models.Q(('url', ''), _negated=True), fields=('owner', 'url'), name='unique_posting_per_url_per_owner'),
        ),
    ]
