# Generated by Django 5.1.4 on 2026-10-09 15:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("ingestion", "0011_backfill_posting_facets"),
    ]

    operations = [
        migrations.AddField(
            model_name="ingestedposting",
            name="latitude",
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="ingestedposting",
            name="longitude",
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="ingestedposting",
            name="posted_at",
            field=models.DateField(blank=True, db_index=True, null=True),
        ),
        migrations.AddField(
            model_name="ingestedposting",
            name="work_arrangement",
            field=models.CharField(blank=True, db_index=True, max_length=10),
        ),
    ]
